const municipalitiesByRegion = {
  "Berner Aargau": [
    "Aarau",
    "Aarburg",
    "Ammerswil",
    "Auenstein",
    "Beinwil am See",
    "Biberstein",
    "Birr",
    "Birrhard",
    "Birrwil",
    "Boniswil",
    "Bottenwil",
    "Bözberg",
    "Brittnau",
    "Brugg",
    "Brunegg",
    "Buchs",
    "Densbüren",
    "Dintikon",
    "Dürrenäsch",
    "Egliswil",
    "Erlinsbach",
    "Fahrwangen",
    "Gontenschwil",
    "Gränichen",
    "Habsburg",
    "Hallwil",
    "Hausen",
    "Hendschiken",
    "Hirschthal",
    "Holderbank",
    "Holziken",
    "Hunzenschwil",
    "Kirchleerau",
    "Kölliken",
    "Küttigen",
    "Leimbach",
    "Lenzburg",
    "Leutwil",
    "Lupfig",
    "Mandach",
    "Meisterschwanden",
    "Menziken",
    "Mönthal",
    "Moosleerau",
    "Möriken-Wildegg",
    "Muhen",
    "Mülligen",
    "Murgenthal",
    "Niederlenz",
    "Oberentfelden",
    "Oberkulm",
    "Oftringen",
    "Othmarsingen",
    "Reinach",
    "Reitnau",
    "Remigen",
    "Riniken",
    "Rothrist",
    "Rüfenach",
    "Rupperswil",
    "Safenwil",
    "Schafisheim",
    "Schinznach",
    "Schlossrued",
    "Schmiedrued",
    "Schöftland",
    "Seengen",
    "Seon",
    "Staffelbach",
    "Staufen",
    "Strengelbach",
    "Suhr",
    "Teufenthal",
    "Thalheim",
    "Uerkheim",
    "Unterentfelden",
    "Unterkulm",
    "Veltheim",
    "Villigen",
    "Vordemwald",
    "Wiliberg",
    "Windisch",
    "Zetzwil",
    "Zofingen"
  ],
  Fricktal: [
    "Böztal",
    "Eiken",
    "Frick",
    "Gansingen",
    "Gipf-Oberfrick",
    "Hellikon",
    "Herznach-Ueken",
    "Kaiseraugst",
    "Kaisten",
    "Laufenburg",
    "Magden",
    "Mettauertal",
    "Möhlin",
    "Mumpf",
    "Münchwilen",
    "Oberhof",
    "Obermumpf",
    "Oeschgen",
    "Olsberg",
    "Rheinfelden",
    "Schupfart",
    "Schwaderloch",
    "Sisseln",
    "Stein",
    "Wallbach",
    "Wegenstetten",
    "Wittnau",
    "Wölflinswil",
    "Zeihen",
    "Zeiningen",
    "Zuzgen"
  ],
  Baden: [
    "Baden",
    "Bellikon",
    "Bergdietikon",
    "Birmenstorf",
    "Böttstein",
    "Döttingen",
    "Ehrendingen",
    "Endingen",
    "Ennetbaden",
    "Fisibach",
    "Fislisbach",
    "Freienwil",
    "Full-Reuenthal",
    "Gebenstorf",
    "Killwangen",
    "Klingnau",
    "Koblenz",
    "Künten",
    "Leibstadt",
    "Lengnau",
    "Leuggern",
    "Mägenwil",
    "Mellikon",
    "Mellingen",
    "Neuenhof",
    "Niederrohrdorf",
    "Oberrohrdorf",
    "Obersiggenthal",
    "Remetschwil",
    "Schneisingen",
    "Siglistorf",
    "Spreitenbach",
    "Stetten",
    "Tägerig",
    "Tegerfelden",
    "Untersiggenthal",
    "Wettingen",
    "Wohlenschwil",
    "Würenlingen",
    "Würenlos",
    "Zurzach"
  ],
  Freiamt: [
    "Abtwil",
    "Aristau",
    "Arni (AG)",
    "Auw",
    "Beinwil (Freiamt)",
    "Berikon",
    "Besenbüren",
    "Bettwil",
    "Boswil",
    "Bremgarten",
    "Bünzen",
    "Büttikon",
    "Buttwil",
    "Dietwil",
    "Dottikon",
    "Eggenwil",
    "Fischbach-Göslikon",
    "Geltwil",
    "Hägglingen",
    "Islisberg",
    "Jonen",
    "Kallern",
    "Merenschwand",
    "Mühlau",
    "Muri",
    "Niederwil",
    "Oberlunkhofen",
    "Oberrüti",
    "Oberwil-Lieli",
    "Rottenschwil",
    "Rudolfstetten-Friedlisberg",
    "Sarmenstorf",
    "Sins",
    "Uezwil",
    "Unterlunkhofen",
    "Villmergen",
    "Waltenschwil",
    "Widen",
    "Wohlen",
    "Zufikon"
  ]
};

const regionByMunicipality = new Map(
  Object.entries(municipalitiesByRegion).flatMap(([region, municipalities]) =>
    municipalities.map((municipality) => [municipality.toLocaleLowerCase("de-CH"), region])
  )
);

const largeProjectPattern =
  /mehrfamilienh(?:aus|äuser)|\bmfh\b|wohnüberbauung|arealüberbauung|überbauung|industrie(?:halle|bau)|gewerbebau|geschäftshaus|schul(?:haus|anlage)|mehrzweckhalle|spital|pflegeheim|hotel|wohn- und geschäftshaus/iu;
const smallProjectPattern =
  /wärmepumpe|photovoltaik|pv-anlage|solaranlage|dachfenster|fensterersatz|reklame|werbeanlage|klimaanlage|ladestation|e-ladestation|sichtschutz|pergola|gartenhaus|geräteschuppen|velounterstand|carport|schwimmbecken|pool|fassaden(?:änderung|anstrich)|dachsanierung/iu;
const mediumProjectPattern =
  /einfamilienhaus|\befh\b|doppeleinfamilienhaus|reihenhaus|anbau|umbau|aufstockung|umnutzung|ersatzneubau|neubau|sanierung|renovation|garage|terrasse|balkon|dachausbau/iu;

export function getApplicationRegion(municipality) {
  const normalizedMunicipality = String(municipality || "").trim().toLocaleLowerCase("de-CH");
  return regionByMunicipality.get(normalizedMunicipality) || "";
}

export function classifyProjectScale(application = {}) {
  const description = [application.projectType, application.description, application.title]
    .filter(Boolean)
    .join(" ");

  if (largeProjectPattern.test(description)) return "gross";
  if (smallProjectPattern.test(description)) return "klein";
  if (mediumProjectPattern.test(description)) return "mittel";
  return "nicht-klassiert";
}
