export const seedApplications = [
  {
    id: "BG-2026-001",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-20-001",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Aarau",
    address: "Bahnhofstrasse 12",
    parcel: "4421",
    coordinates: "2659108,1248179",
    publicationDate: "2026-03-20",
    deadlineDate: "2026-03-25",
    projectType: "Umbau Fassade und Dachaufbauten",
    description: "Umbau eines Wohn- und Geschäftshauses mit Eingriff in die Strassenfassade.",
    protectionStatus: "combined-hit",
    agisMatch: "ISOS-Fläche und Gebäude im Inventar",
    agisLayers: ["ISOS-Fläche", "Gebäude im Inventar"],
    workflowStatus: "under-review",
    assignee: "Lucia Vettori",
    note: "Historische Wirkung im Strassenbild prüfen und Bestandesunterlagen vergleichen.",
    automatedAssessment: "Adresse erfolgreich dem AGIS-Objekt zugeordnet. Relevanter Schutztreffer vorhanden.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-002",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-20-002",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Baden",
    address: "Mellingerstrasse 7",
    parcel: "1189",
    coordinates: "2670711,1258241",
    publicationDate: "2026-03-20",
    deadlineDate: "2026-03-28",
    projectType: "Fenstersanierung",
    description: "Ersatz der bestehenden Fensterfront gegen moderne Holz-Metall-Fenster.",
    protectionStatus: "no-hit",
    agisMatch: "Kein Schutztreffer",
    agisLayers: [],
    workflowStatus: "new",
    assignee: "Team Baden",
    note: "",
    automatedAssessment: "Kein Treffer in den relevanten AGIS-Layern festgestellt.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-003",
    source: "Gemeindeseite",
    sourceReference: "GS-ZOF-2026-014",
    sourceUrl: "https://www.ag.ch/de/themen/planen-bauen/raumentwicklung/grundlagen-und-kantonalplanung/online-karten",
    municipality: "Zofingen",
    address: "Kirchplatz 4",
    parcel: "301",
    coordinates: "2635744,1237998",
    publicationDate: "2026-03-18",
    deadlineDate: "2026-03-22",
    projectType: "Dachsanierung",
    description: "Erneuerung der Dachhaut mit gaubenartigem Aufbau auf der Hofseite.",
    protectionStatus: "protected-point",
    agisMatch: "Treffer im Gebäudeinventar",
    agisLayers: ["Gebäude im Inventar"],
    workflowStatus: "new",
    assignee: "",
    note: "",
    automatedAssessment: "Der Standort wurde einem geschützten Inventarobjekt zugeordnet.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-004",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-19-004",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Lenzburg",
    address: "Burghaldenstrasse",
    parcel: "",
    coordinates: "",
    publicationDate: "2026-03-19",
    deadlineDate: "2026-03-27",
    projectType: "Neubau Einfamilienhaus",
    description: "Neubauprojekt mit unvollständiger Adressangabe in der Publikation.",
    protectionStatus: "manual-review",
    agisMatch: "Noch nicht eindeutig zugeordnet",
    agisLayers: [],
    workflowStatus: "under-review",
    assignee: "Momik",
    note: "Adresse reicht für eindeutige Parzellenzuordnung nicht aus. Manuelle Klärung nötig.",
    automatedAssessment: "Automatische Zuordnung blockiert, weil nur Strassenname ohne Hausnummer publiziert wurde.",
    ambiguousAddress: 1
  },
  {
    id: "BG-2026-005",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-17-005",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Brugg",
    address: "Hauptstrasse 44",
    parcel: "877",
    coordinates: "2651766,1250865",
    publicationDate: "2026-03-17",
    deadlineDate: "2026-03-24",
    projectType: "Anbau Wintergarten",
    description: "Anbau eines Wintergartens auf der Rückseite eines Altstadthauses.",
    protectionStatus: "protected-zone",
    agisMatch: "Treffer in ISOS-Fläche",
    agisLayers: ["ISOS-Fläche"],
    workflowStatus: "under-review",
    assignee: "ARK Team",
    note: "Rückfrage, ob Wirkung im Ortsbild ausreichend dokumentiert ist.",
    automatedAssessment: "Der Standort liegt innerhalb einer AGIS-Schutzfläche.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-006",
    source: "Gemeindeseite",
    sourceReference: "GS-WET-2026-008",
    sourceUrl: "https://www.ag.ch/de/themen/planen-bauen/raumentwicklung/grundlagen-und-kantonalplanung/online-karten",
    municipality: "Wettingen",
    address: "Landstrasse 120",
    parcel: "5220",
    coordinates: "2663841,1258254",
    publicationDate: "2026-03-15",
    deadlineDate: "2026-03-30",
    projectType: "Innenausbau Ladengeschäft",
    description: "Umnutzung eines Erdgeschosses ohne sichtbare Aussenveränderung.",
    protectionStatus: "no-hit",
    agisMatch: "Kein Schutztreffer",
    agisLayers: [],
    workflowStatus: "cleared",
    assignee: "Team Wettingen",
    note: "Kein weiterer Handlungsbedarf.",
    automatedAssessment: "Weder Inventarobjekt noch ISOS-Fläche betroffen.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-007",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-14-007",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Rheinfelden",
    address: "Marktgasse 2",
    parcel: "990",
    coordinates: "2672321,1270914",
    publicationDate: "2026-03-14",
    deadlineDate: "2026-03-21",
    projectType: "Umbau Schaufenster",
    description: "Anpassung der Schaufensterfront eines denkmalrelevanten Gebäudes.",
    protectionStatus: "protected-point",
    agisMatch: "Treffer im Gebäudeinventar",
    agisLayers: ["Gebäude im Inventar"],
    workflowStatus: "archived",
    assignee: "Lucia Vettori",
    note: "Fall bereits abgeschlossen und archiviert.",
    automatedAssessment: "Historisch relevantes Einzelobjekt erkannt.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-008",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-13-008",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Muri",
    address: "Klosterhof 1",
    parcel: "77",
    coordinates: "2672834,1233158",
    publicationDate: "2026-03-13",
    deadlineDate: "2026-03-26",
    projectType: "Aussenbeleuchtung",
    description: "Neue Aussenbeleuchtung entlang eines sensiblen historischen Ensembles.",
    protectionStatus: "protected-zone",
    agisMatch: "Treffer in ISOS-Fläche",
    agisLayers: ["ISOS-Fläche"],
    workflowStatus: "new",
    assignee: "Team Muri",
    note: "",
    automatedAssessment: "Der Standort liegt innerhalb einer AGIS-Schutzfläche.",
    ambiguousAddress: 0
  }
];

export const importQueue = [
  {
    id: "BG-2026-009",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-21-009",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Aarau",
    address: "Rathausgasse 9",
    parcel: "450",
    coordinates: "2659010,1248124",
    publicationDate: "2026-03-21",
    deadlineDate: "2026-03-29",
    projectType: "Balkonerweiterung",
    description: "Geplanter Balkonanbau an einem Altstadtobjekt.",
    protectionStatus: "protected-point",
    agisMatch: "Treffer im Gebäudeinventar",
    agisLayers: ["Gebäude im Inventar"],
    workflowStatus: "new",
    assignee: "",
    note: "",
    automatedAssessment: "Neues Amtsblatt-Gesuch automatisch mit Inventarobjekt verknüpft.",
    ambiguousAddress: 0
  },
  {
    id: "BG-2026-010",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-21-010",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Bremgarten",
    address: "Rechengasse",
    parcel: "",
    coordinates: "",
    publicationDate: "2026-03-21",
    deadlineDate: "2026-03-31",
    projectType: "Abbruch Nebenbau",
    description: "Publikation ohne Hausnummer oder Parzellenangabe.",
    protectionStatus: "manual-review",
    agisMatch: "Zuordnung offen",
    agisLayers: [],
    workflowStatus: "new",
    assignee: "",
    note: "",
    automatedAssessment: "Automatische Zuordnung gescheitert, da die Publikation keine eindeutige Objektadresse enthält.",
    ambiguousAddress: 1
  },
  {
    id: "BG-2026-011",
    source: "Amtsblatt",
    sourceReference: "AB-2026-03-21-011",
    sourceUrl: "https://amtsblatt.ag.ch/publikationen/",
    municipality: "Sarmenstorf",
    address: "Bachstrasse 2",
    parcel: "102",
    coordinates: "2677163,1239922",
    publicationDate: "2026-03-21",
    deadlineDate: "2026-04-01",
    projectType: "Solaranlage Dach",
    description: "Anlage auf einem Gebäude ausserhalb relevanter Schutzlayer.",
    protectionStatus: "no-hit",
    agisMatch: "Kein Schutztreffer",
    agisLayers: [],
    workflowStatus: "new",
    assignee: "",
    note: "",
    automatedAssessment: "Keine relevanten AGIS-Treffer. Fall kann wahrscheinlich freigegeben werden.",
    ambiguousAddress: 0
  }
];
